"use client";
import Link from "next/link";
import { motion, useScroll, useTransform } from "motion/react";
import { contact, projects, services, site, technologies } from "@/data/site";
import { Header } from "./header";
import { Intro } from "./intro";
import { ProductVisual } from "./product-visual";
import { Estimator } from "./estimator";
import { Reveal } from "./reveal";
import { Arrow } from "./icons";

export function Home() {
  const { scrollYProgress } = useScroll();
  const gridY = useTransform(scrollYProgress, [0, 1], [0, 240]);
  return <main><Intro/><Header/><section className="hero hero-v2"><motion.div className="system-grid" style={{ y: gridY }}><i/><i/><i/><i/><span className="signal s1"/><span className="signal s2"/></motion.div><div className="hero-stage"><div className="hero-copy"><div className="hero-badge"><i/> BUSINESS SOFTWARE <span>\</span> DIGITAL PRODUCTS</div><p className="hero-path">IDEA <span>→</span> DESIGN <span>→</span> DEVELOPMENT <span>→</span> IMPACT</p><h1>I turn business <strong>problems</strong> into working software.</h1><p className="hero-description">CRM, POS, business websites and custom applications designed around real business workflows.</p><div className="hero-actions"><a className="button primary" href="#work">View My Work <Arrow/></a><a className="button ghost" href="#contact">Start a Project <Arrow/></a></div><div className="hero-proof"><div><b>04</b><span>Projects<br/>Delivered</span></div><div><b>05</b><span>Product<br/>Categories</span></div><div><b>06</b><span>Connected<br/>Stages</span></div></div></div><div className="hero-showcase" aria-label="Selected product interface previews"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="showcase-card showcase-crm"><ProductVisual project={projects[0]}/><span>DEALUP CRM <i>Sales Growth</i></span></div><div className="showcase-card showcase-pos"><ProductVisual project={projects[1]}/><span>DRIP POS <i>Retail Simplified</i></span></div><div className="showcase-card showcase-auto"><ProductVisual project={projects[2]}/><span>DK DETAILING <i>Business OS</i></span></div><div className="showcase-card showcase-web"><ProductVisual project={projects[3]}/><span>PREMIUM WEBSITE <i>Stronger Brand</i></span></div><p className="showcase-note note-one">Real problems.<br/>Real solutions.</p></div></div><a className="scroll-cue" href="#work">SCROLL TO EXPLORE <i>↓</i></a></section>

  <section className="work section" id="work"><Reveal className="section-intro"><p className="eyebrow">SELECTED WORK / 04 PRODUCTS</p><h2>Products designed around<br/>real business workflows.</h2></Reveal><div className="project-list">{projects.map((p) => <article className={`project theme-${p.theme}`} key={p.slug}><div className="project-heading"><span>{p.number}</span><div><p>{p.category}</p><h3>{p.name}</h3></div><Link href={`/work/${p.slug}`} aria-label={`View ${p.name} case study`}><Arrow diagonal/></Link></div><Link href={`/work/${p.slug}`} className="visual-link" aria-label={`Open ${p.name} case study`}><ProductVisual project={p}/></Link><div className="project-foot"><p>{p.summary}</p><Link href={`/work/${p.slug}`}>VIEW CASE STUDY <Arrow/></Link></div></article>)}</div></section>

  <section className="services section" id="services"><Reveal className="section-intro split"><div><p className="eyebrow">CAPABILITIES / 05</p><h2>What I build.</h2></div><p>Practical digital products shaped around the systems, people and decisions that keep a business moving.</p></Reveal><div className="service-list">{services.map(([name, price], i) => <div className="service-row" key={name}><span>0{i+1}</span><h3>{name}</h3><p>Starting ₹{(price/1000).toFixed(0)},000+</p><Arrow diagonal/></div>)}</div><p className="pricing-note">Final pricing depends on scope, modules, integrations and support requirements.</p></section>

  <Estimator/>

  <section className="pricing section" id="pricing"><Reveal className="section-intro"><p className="eyebrow">ENGAGEMENT OPTIONS</p><h2>A clear place to start.</h2></Reveal><div className="price-grid">{[["STARTER","25K","Focused websites or lightweight business systems."],["BUSINESS","40K","Database-backed applications, dashboards, CRM/POS functionality and business workflows."],["CUSTOM","60K","Advanced custom applications, multiple modules, integrations, roles and complex workflows."]].map(([name,price,copy],i) => <article className={i===1 ? "price-card featured" : "price-card"} key={name}>{i===1 && <span className="popular">MOST POPULAR</span>}<p>{name}</p><h3><small>Starting</small> ₹{price}</h3><p>{copy}</p><a href="#contact">DISCUSS PROJECT <Arrow/></a></article>)}</div></section>

  <section className="process section" id="process"><Reveal className="section-intro split"><div><p className="eyebrow">HOW IT COMES TOGETHER</p><h2>From friction<br/>to finished product.</h2></div><p>A connected process keeps every design decision tied to the business workflow it needs to improve.</p></Reveal><div className="process-line">{[["DISCOVERY","Understand the business and workflow."],["PRODUCT PLANNING","Define modules, screens and user journeys."],["DESIGN","Build the visual system and interactions."],["DEVELOPMENT","Build the working application."],["TESTING","Validate workflows, responsiveness and edge cases."],["DEPLOYMENT","Launch the production application."]].map(([name,copy],i) => <div className="process-step" key={name}><span>0{i+1}</span><i/><h3>{name}</h3><p>{copy}</p></div>)}</div></section>

  <section className="tech section"><p className="eyebrow">TECHNOLOGY / SUPPORTING THE PRODUCT</p><div className="tech-list">{technologies.map((t) => <span key={t}>{t}</span>)}</div></section>

  <section className="about section" id="about"><div className="about-mark"><span>BUSINESS</span><span>×</span><span>SOFTWARE</span></div><Reveal><p className="eyebrow">THE APPROACH</p><h2>Software built around the way businesses actually work.</h2><p className="about-copy">My focus is understanding a business workflow first, then designing the software around it.</p></Reveal></section>

  <section className="contact section" id="contact"><p className="eyebrow">LET’S BUILD SOMETHING USEFUL</p><h2>Have a business problem<br/>worth solving?</h2><p>Tell me how your business works today and what you want to improve.</p><div className="contact-actions">{contact.email ? <a className="button light" href={`mailto:${contact.email}`}>START A PROJECT <Arrow/></a> : <a className="button light" href="#services">EXPLORE SERVICES <Arrow/></a>}{contact.whatsappHref ? <a className="button line" href={contact.whatsappHref} target="_blank" rel="noreferrer">WHATSAPP <Arrow diagonal/></a> : null}{contact.email ? <a className="button line" href={`mailto:${contact.email}`}>EMAIL <Arrow diagonal/></a> : null}</div><footer><span>{site.brand}</span><span>{site.title.toUpperCase()}</span><span>© {new Date().getFullYear()}</span></footer></section></main>;
}
